In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../warehouse/payments_warehouse.db")

def run(query):
    return pd.read_sql(query, conn)

In [6]:
def run_file(filepath):
    with open(filepath, "r") as f:
        query = f.read()
    return run(query)

In [7]:
df_q1 = run_file("../sql/queries/01_daily_tpv.sql")
df_q1

      full_date  daily_tpv  txn_count
0    2024-01-01     881371        665
1    2024-01-02     896546        707
2    2024-01-03     868891        638
3    2024-01-04     820257        661
4    2024-01-05     931644        705
..          ...        ...        ...
360  2024-12-26     902031        678
361  2024-12-27     978239        676
362  2024-12-28     891217        685
363  2024-12-29     851014        668
364  2024-12-30     972740        716

[365 rows x 3 columns]

In [8]:
df_q2 = run_file("../sql/queries/02_monthly_tpv_mom_growth.sql")
df_q2

    year  month month_name  monthly_tpv  mom_growth_pct
0   2024      1    January     27456691             NaN
1   2024      2   February     25826330           -5.94
2   2024      3      March     27508202            6.51
3   2024      4      April     26988791           -1.89
4   2024      5        May     28024857            3.84
5   2024      6       June     27032118           -3.54
6   2024      7       July     28079905            3.88
7   2024      8     August     27845907           -0.83
8   2024      9  September     27105761           -2.66
9   2024     10    October     27866829            2.81
10  2024     11   November     26892531           -3.50
11  2024     12   December     27311087            1.56

In [9]:
df_q3 = run_file("../sql/queries/03_merchant_category_tpv_share.sql")
df_q3

  merchant_category       tpv  txn_count  pct_of_total_tpv
0          Shopping  76863207      29872             23.44
1           Grocery  58277893      49966             17.77
2         Utilities  52742482      22338             16.08
3              Fuel  38982575      25063             11.89
4         Education  38704346       7598             11.80
5             Other  21073449      24828              6.43
6              Food  19919402      37464              6.07
7     Entertainment   8309080      20103              2.53
8        Healthcare   6874159      12663              2.10
9         Transport   6192416      20105              1.89

In [10]:
df_q4 = run_file("../sql/queries/04_merchant_category_monthly_trend.sql")
df_q4

    merchant_category  month month_name  monthly_tpv
0           Education      1    January      3358450
1           Education      2   February      2832813
2           Education      3      March      3199426
3           Education      4      April      3146141
4           Education      5        May      3341950
..                ...    ...        ...          ...
115         Utilities      8     August      4684127
116         Utilities      9  September      4290727
117         Utilities     10    October      4654883
118         Utilities     11   November      4235031
119         Utilities     12   December      4437394

[120 rows x 4 columns]

In [11]:
df_q5 = run_file("../sql/queries/05_p2p_vs_p2m_growth.sql")
df_q5

   transaction_type  month  monthly_tpv  txn_count
0               P2M      1      9699161       7386
1               P2M      2      9117814       7051
2               P2M      3      9462083       7377
3               P2M      4      9778199       7234
4               P2M      5      9828259       7485
5               P2M      6      9941921       7310
6               P2M      7     10006118       7453
7               P2M      8      9514223       7298
8               P2M      9      9537521       7166
9               P2M     10      9878728       7450
10              P2M     11      9377372       7136
11              P2M     12      9576168       7314
12              P2P      1     12290267       9668
13              P2P      2     11653281       8834
14              P2P      3     12576103       9582
15              P2P      4     11773538       9118
16              P2P      5     12665154       9635
17              P2P      6     11931059       9188
18              P2P      7     12856745       9692
19              P2P      8     12493292       9571
20              P2P      9     12231509       9308
21              P2P     10     12497405       9508
22              P2P     11     11928869       9094
23              P2P     12     12257426       9247

In [12]:
df_q6 = run_file("../sql/queries/06_top5_states_tpv_share.sql")
df_q6

    sender_state       tpv  pct_share
0    Maharashtra  49043948      14.96
1  Uttar Pradesh  40035717      12.21
2      Karnataka  38451158      11.73
3     Tamil Nadu  33343518      10.17
4          Delhi  32689865       9.97

In [13]:
df_q7 = run_file("../sql/queries/07_weekend_vs_weekday_tpv.sql")
df_q7

   is_weekend        tpv  txn_count  avg_txn_value
0           0  234498529     178663        1312.52
1           1   93440480      71337        1309.85

In [14]:
df_q8 = run_file("../sql/queries/08_cumulative_tpv_running_total.sql")
df_q8

      full_date  daily_tpv  cumulative_tpv
0    2024-01-01     881371          881371
1    2024-01-02     896546         1777917
2    2024-01-03     868891         2646808
3    2024-01-04     820257         3467065
4    2024-01-05     931644         4398709
..          ...        ...             ...
360  2024-12-26     902031       324245799
361  2024-12-27     978239       325224038
362  2024-12-28     891217       326115255
363  2024-12-29     851014       326966269
364  2024-12-30     972740       327939009

[365 rows x 3 columns]

In [15]:
df_q9 = run_file("../sql/queries/09_success_rate_monthly.sql")
df_q9

    year  month month_name  total_txns  successful_txns  success_rate_pct
0   2024      1    January       21221            20209             95.23
1   2024      2   February       19759            18805             95.17
2   2024      3      March       21234            20092             94.62
3   2024      4      April       20536            19527             95.09
4   2024      5        May       21333            20295             95.13
5   2024      6       June       20628            19588             94.96
6   2024      7       July       21207            20146             95.00
7   2024      8     August       21231            20198             95.13
8   2024      9  September       20597            19536             94.85
9   2024     10    October       21252            20245             95.26
10  2024     11   November       20366            19357             95.05
11  2024     12   December       20636            19626             95.11

In [16]:
df_q10 = run_file("../sql/queries/10_success_rate_by_category.sql")
df_q10

  merchant_category  total_txns  success_rate_pct
0         Education        7598             94.75
1          Shopping       29872             94.91
2              Food       37464             94.99
3           Grocery       49966             94.99
4             Other       24828             95.05
5     Entertainment       20103             95.08
6         Utilities       22338             95.14
7        Healthcare       12663             95.17
8              Fuel       25063             95.20
9         Transport       20105             95.24

In [17]:
df_q11 = run_file("../sql/queries/11_success_rate_by_state.sql")
df_q11

     sender_state  total_txns  success_rate_pct
0   Uttar Pradesh       30125             94.78
1      Tamil Nadu       25367             94.88
2     West Bengal       19972             94.96
3  Andhra Pradesh       20006             95.00
4           Delhi       24870             95.03
5     Maharashtra       37427             95.08
6       Karnataka       29756             95.14
7       Rajasthan       19981             95.21
8         Gujarat       20061             95.22
9       Telangana       22435             95.29

In [18]:
df_q12 = run_file("../sql/queries/12_success_rate_by_network.sql")
df_q12

  network_type  total_txns  success_rate_pct
0           3G       12471             94.78
1           4G      149813             95.02
2           5G       62582             95.14
3         WiFi       25134             95.14

In [24]:
df_q13 = run_file("../sql/queries/13_success_rate_by_device.sql")
df_q13.sort_values("total_txns")
df_q13

  device_type  total_txns  success_rate_pct
0         Web       12610             94.85
1     Android      187777             95.06
2         iOS       49613             95.07

In [20]:
df_q14 = run_file("../sql/queries/14_success_rate_by_hour.sql")
df_q14

    hour_of_day  total_txns  success_rate_pct
0             0        3388             94.63
1             1        2244             94.65
2             2        1685             94.84
3             3        1314             94.98
4             4        1247             94.87
5             5        1742             95.46
6             6        3501             94.60
7             7        5630             95.12
8             8        8349             94.99
9             9       10450             95.19
10           10       13904             94.81
11           11       16328             95.04
12           12       17516             95.00
13           13       15038             95.23
14           14       11472             95.03
15           15       12624             94.88
16           16       13992             95.34
17           17       18340             95.03
18           18       20064             95.15
19           19       21232             94.85
20           20       18506             95.12
21           21       16253             95.25
22           22        9364             94.97
23           23        5817             95.22

In [23]:
df_q15 = run_file("../sql/queries/15_success_rate_network_x_device.sql")
df_q15
df_q15.sort_values("total_txns")

   network_type device_type  total_txns  success_rate_pct
0            3G         Web         636             93.40
3          WiFi         Web        1290             94.96
10           3G         iOS        2394             95.20
4            5G         Web        3165             94.98
11         WiFi         iOS        4979             95.28
2            4G         Web        7519             94.89
1            3G     Android        9441             94.77
7            5G         iOS       12359             95.10
8          WiFi     Android       18865             95.11
5            4G         iOS       29881             95.01
9            5G     Android       47058             95.17
6            4G     Android      112413             95.03

In [22]:
df_q16 = run_file("../sql/queries/16_failure_rate_trend_mom.sql")
df_q16

    month month_name  failure_rate_pct  prev_month_failure_rate_pct
0       1    January              4.77                          NaN
1       2   February              4.83                         4.77
2       3      March              5.38                         4.83
3       4      April              4.91                         5.38
4       5        May              4.87                         4.91
5       6       June              5.04                         4.87
6       7       July              5.00                         5.04
7       8     August              4.87                         5.00
8       9  September              5.15                         4.87
9      10    October              4.74                         5.15
10     11   November              4.95                         4.74
11     12   December              4.89                         4.95

In [30]:
df_q17 = run_file("../sql/queries/17_segment_frequency_monetary.sql")
df_q17

      sender_state age_group  frequency  monetary_total  avg_txn_value
0      Maharashtra     26-35      13029        17379218        1333.89
1    Uttar Pradesh     26-35      10528        14347595        1362.80
2      Maharashtra     36-45       9472        13390131        1413.65
3        Karnataka     26-35      10464        13272595        1268.41
4       Tamil Nadu     26-35       8979        12210450        1359.89
5            Delhi     26-35       8658        11376877        1314.03
6      Maharashtra     18-25       9418        11364225        1206.65
7    Uttar Pradesh     36-45       7510        10809480        1439.34
8        Telangana     26-35       7784        10486900        1347.24
9        Karnataka     36-45       7437        10416560        1400.64
10     West Bengal     26-35       7049         9369305        1329.17
11       Rajasthan     26-35       6944         9262568        1333.90
12         Gujarat     26-35       7040         9209622        1308.18
13           Delhi     36-45       6326         9097178        1438.06
14  Andhra Pradesh     26-35       6957         9044641        1300.08
15   Uttar Pradesh     18-25       7658         9017684        1177.55
16      Tamil Nadu     36-45       6383         8900068        1394.34
17       Karnataka     18-25       7344         8778267        1195.30
18       Telangana     36-45       5572         8041878        1443.27
19       Rajasthan     36-45       5158         7567965        1467.23
20           Delhi     18-25       6170         7532944        1220.90
21      Tamil Nadu     18-25       6306         7354192        1166.22
22         Gujarat     36-45       5010         7226138        1442.34
23  Andhra Pradesh     36-45       5003         7060667        1411.29
24     West Bengal     36-45       5002         7023680        1404.17
25       Telangana     18-25       5613         6877080        1225.21
26  Andhra Pradesh     18-25       4991         5999132        1201.99
27       Rajasthan     18-25       4871         5919864        1215.33
28     West Bengal     18-25       4994         5824837        1166.37
29         Gujarat     18-25       4980         5805711        1165.81
30     Maharashtra     46-55       3719         4877603        1311.54
31   Uttar Pradesh     46-55       2999         4115520        1372.30
32       Karnataka     46-55       2949         4020987        1363.51
33      Tamil Nadu     46-55       2466         3321900        1347.08
34           Delhi     46-55       2428         3223280        1327.55
35       Telangana     46-55       2275         2967559        1304.42
36       Rajasthan     46-55       1996         2716495        1360.97
37  Andhra Pradesh     46-55       1998         2634414        1318.53
38         Gujarat     46-55       2032         2633667        1296.10
39     West Bengal     46-55       1979         2604836        1316.24
40     Maharashtra       56+       1789         2032771        1136.26
41       Karnataka       56+       1562         1962749        1256.56
42   Uttar Pradesh       56+       1430         1745438        1220.59
43      Tamil Nadu       56+       1233         1556908        1262.70
44           Delhi       56+       1288         1459586        1133.22
45       Telangana       56+       1191         1377513        1156.60
46       Rajasthan       56+       1012         1263578        1248.59
47  Andhra Pradesh       56+       1057         1213765        1148.31
48     West Bengal       56+        948         1129936        1191.92
49         Gujarat       56+        999         1113052        1114.17

In [27]:
run("PRAGMA table_info(dim_age_group);")

   cid           name     type  notnull dflt_value  pk
0    0  age_group_key  INTEGER        0       None   1
1    1      age_group     TEXT        1       None   0

In [28]:
run("PRAGMA table_info(dim_geography);")

   cid              name     type  notnull dflt_value  pk
0    0  sender_state_key  INTEGER        0       None   1
1    1      sender_state     TEXT        1       None   0

In [31]:
df_q18 = run_file("../sql/queries/18_segment_recency.sql")
df_q18

      sender_state age_group last_transaction_date  days_since_last_txn
0   Andhra Pradesh     18-25            2024-12-30                    1
1   Andhra Pradesh     26-35            2024-12-30                    1
2   Andhra Pradesh     36-45            2024-12-30                    1
3   Andhra Pradesh     46-55            2024-12-30                    1
4   Andhra Pradesh       56+            2024-12-30                    1
5            Delhi     18-25            2024-12-30                    1
6            Delhi     26-35            2024-12-30                    1
7            Delhi     36-45            2024-12-30                    1
8            Delhi     46-55            2024-12-30                    1
9            Delhi       56+            2024-12-30                    1
10         Gujarat     18-25            2024-12-30                    1
11         Gujarat     26-35            2024-12-30                    1
12         Gujarat     36-45            2024-12-30                    1
13         Gujarat     46-55            2024-12-30                    1
14         Gujarat       56+            2024-12-30                    1
15       Karnataka     18-25            2024-12-30                    1
16       Karnataka     26-35            2024-12-30                    1
17       Karnataka     36-45            2024-12-30                    1
18       Karnataka     46-55            2024-12-30                    1
19       Karnataka       56+            2024-12-30                    1
20     Maharashtra     18-25            2024-12-30                    1
21     Maharashtra     26-35            2024-12-30                    1
22     Maharashtra     36-45            2024-12-30                    1
23     Maharashtra     46-55            2024-12-30                    1
24     Maharashtra       56+            2024-12-30                    1
25       Rajasthan     18-25            2024-12-30                    1
26       Rajasthan     26-35            2024-12-30                    1
27       Rajasthan     36-45            2024-12-30                    1
28       Rajasthan     46-55            2024-12-30                    1
29       Rajasthan       56+            2024-12-30                    1
30      Tamil Nadu     18-25            2024-12-30                    1
31      Tamil Nadu     26-35            2024-12-30                    1
32      Tamil Nadu     36-45            2024-12-30                    1
33      Tamil Nadu     46-55            2024-12-30                    1
34      Tamil Nadu       56+            2024-12-30                    1
35       Telangana     18-25            2024-12-30                    1
36       Telangana     26-35            2024-12-30                    1
37       Telangana     36-45            2024-12-30                    1
38       Telangana     46-55            2024-12-30                    1
39       Telangana       56+            2024-12-30                    1
40   Uttar Pradesh     18-25            2024-12-30                    1
41   Uttar Pradesh     26-35            2024-12-30                    1
42   Uttar Pradesh     36-45            2024-12-30                    1
43   Uttar Pradesh     46-55            2024-12-30                    1
44   Uttar Pradesh       56+            2024-12-30                    1
45     West Bengal     18-25            2024-12-30                    1
46     West Bengal     26-35            2024-12-30                    1
47     West Bengal     36-45            2024-12-30                    1
48     West Bengal     46-55            2024-12-30                    1
49     West Bengal       56+            2024-12-30                    1

In [39]:
df_q19 = run_file("../sql/queries/19_segment_rfm_combined.sql")
df_q19.to_csv("../data/processed/segment_rfm.csv", index=False)
df_q19

      sender_state age_group  frequency  monetary_total  avg_txn_value
0      Maharashtra     26-35      13029        17379218        1333.89
1    Uttar Pradesh     26-35      10528        14347595        1362.80
2      Maharashtra     36-45       9472        13390131        1413.65
3        Karnataka     26-35      10464        13272595        1268.41
4       Tamil Nadu     26-35       8979        12210450        1359.89
5            Delhi     26-35       8658        11376877        1314.03
6      Maharashtra     18-25       9418        11364225        1206.65
7    Uttar Pradesh     36-45       7510        10809480        1439.34
8        Telangana     26-35       7784        10486900        1347.24
9        Karnataka     36-45       7437        10416560        1400.64
10     West Bengal     26-35       7049         9369305        1329.17
11       Rajasthan     26-35       6944         9262568        1333.90
12         Gujarat     26-35       7040         9209622        1308.18
13           Delhi     36-45       6326         9097178        1438.06
14  Andhra Pradesh     26-35       6957         9044641        1300.08
15   Uttar Pradesh     18-25       7658         9017684        1177.55
16      Tamil Nadu     36-45       6383         8900068        1394.34
17       Karnataka     18-25       7344         8778267        1195.30
18       Telangana     36-45       5572         8041878        1443.27
19       Rajasthan     36-45       5158         7567965        1467.23
20           Delhi     18-25       6170         7532944        1220.90
21      Tamil Nadu     18-25       6306         7354192        1166.22
22         Gujarat     36-45       5010         7226138        1442.34
23  Andhra Pradesh     36-45       5003         7060667        1411.29
24     West Bengal     36-45       5002         7023680        1404.17
25       Telangana     18-25       5613         6877080        1225.21
26  Andhra Pradesh     18-25       4991         5999132        1201.99
27       Rajasthan     18-25       4871         5919864        1215.33
28     West Bengal     18-25       4994         5824837        1166.37
29         Gujarat     18-25       4980         5805711        1165.81
30     Maharashtra     46-55       3719         4877603        1311.54
31   Uttar Pradesh     46-55       2999         4115520        1372.30
32       Karnataka     46-55       2949         4020987        1363.51
33      Tamil Nadu     46-55       2466         3321900        1347.08
34           Delhi     46-55       2428         3223280        1327.55
35       Telangana     46-55       2275         2967559        1304.42
36       Rajasthan     46-55       1996         2716495        1360.97
37  Andhra Pradesh     46-55       1998         2634414        1318.53
38         Gujarat     46-55       2032         2633667        1296.10
39     West Bengal     46-55       1979         2604836        1316.24
40     Maharashtra       56+       1789         2032771        1136.26
41       Karnataka       56+       1562         1962749        1256.56
42   Uttar Pradesh       56+       1430         1745438        1220.59
43      Tamil Nadu       56+       1233         1556908        1262.70
44           Delhi       56+       1288         1459586        1133.22
45       Telangana       56+       1191         1377513        1156.60
46       Rajasthan       56+       1012         1263578        1248.59
47  Andhra Pradesh       56+       1057         1213765        1148.31
48     West Bengal       56+        948         1129936        1191.92
49         Gujarat       56+        999         1113052        1114.17

In [33]:
df_q20 = run_file("../sql/queries/20_weekend_vs_weekday_by_category.sql")
df_q20

   merchant_category  is_weekend       tpv  txn_count  avg_txn_value
0          Education           0  27421563       5346        5129.36
1          Education           1  11282783       2252        5010.12
2      Entertainment           0   5945548      14358         414.09
3      Entertainment           1   2363532       5745         411.41
4               Food           0  14269853      26824         531.98
5               Food           1   5649549      10640         530.97
6               Fuel           0  27812833      17832        1559.71
7               Fuel           1  11169742       7231        1544.70
8            Grocery           0  41491984      35679        1162.92
9            Grocery           1  16785909      14287        1174.91
10        Healthcare           0   4906529       9056         541.80
11        Healthcare           1   1967630       3607         545.50
12             Other           0  15244685      17813         855.82
13             Other           1   5828764       7015         830.90
14          Shopping           0  55174550      21336        2585.98
15          Shopping           1  21688657       8536        2540.85
16         Transport           0   4428247      14415         307.20
17         Transport           1   1764169       5690         310.05
18         Utilities           0  37802737      16004        2362.08
19         Utilities           1  14939745       6334        2358.66

In [34]:
df_q21 = run_file("../sql/queries/21_peak_hours_by_category.sql")
df_q21

    merchant_category  hour_of_day  txn_count      tpv
0           Education            0        112   576470
1           Education            1         59   336968
2           Education            2         46   229566
3           Education            3         38   193912
4           Education            4         38   220968
..                ...          ...        ...      ...
235         Utilities           19       1825  4391254
236         Utilities           20       1631  3801458
237         Utilities           21       1462  3363235
238         Utilities           22        832  1937047
239         Utilities           23        531  1318970

[240 rows x 4 columns]

In [35]:
df_q22 = run_file("../sql/queries/22_avg_txn_value_by_age_group.sql")
df_q22

  age_group  txn_count  total_spend  avg_txn_value
0     36-45      62873     89533745        1424.04
1     46-55      24841     33116261        1333.13
2     26-35      87432    115959771        1326.29
3     18-25      62345     74473936        1194.55
4       56+      12509     14855296        1187.57

In [36]:
df_q23 = run_file("../sql/queries/23_top_segments_by_tpv.sql")
df_q23

    sender_state age_group       tpv  txn_count  pct_of_total_tpv
0    Maharashtra     26-35  17379218      13029              5.30
1  Uttar Pradesh     26-35  14347595      10528              4.38
2    Maharashtra     36-45  13390131       9472              4.08
3      Karnataka     26-35  13272595      10464              4.05
4     Tamil Nadu     26-35  12210450       8979              3.72
5          Delhi     26-35  11376877       8658              3.47
6    Maharashtra     18-25  11364225       9418              3.47
7  Uttar Pradesh     36-45  10809480       7510              3.30
8      Telangana     26-35  10486900       7784              3.20
9      Karnataka     36-45  10416560       7437              3.18

In [37]:
df_q24 = run_file("../sql/queries/24_device_network_usage_by_age_group.sql")
df_q24

   age_group device_type  txn_count  pct_within_age_group
0      18-25     Android      46848                 75.14
1      18-25         Web       3159                  5.07
2      18-25         iOS      12338                 19.79
3      26-35     Android      65466                 74.88
4      26-35         Web       4484                  5.13
5      26-35         iOS      17482                 19.99
6      36-45     Android      47288                 75.21
7      36-45         Web       3143                  5.00
8      36-45         iOS      12442                 19.79
9      46-55     Android      18724                 75.38
10     46-55         Web       1219                  4.91
11     46-55         iOS       4898                 19.72
12       56+     Android       9451                 75.55
13       56+         Web        605                  4.84
14       56+         iOS       2453                 19.61